### ISSUE TITLE
load bert model generate text embedding error

### ISSUE THREAD

**Issue by yjh01** [deepjavalibrary/djl-demo#346]
i use djl 0.21.1 to load bert-base-cased model, to get text embedding.
but processOutput ndlist shape is (tokens_siize,bert-base-cased_vocab.size)  not  hidden_size

bert-base-cased  model is convert by model_zoo_importer.py from huggingface
link:  https://huggingface.co/bert-base-cased
config.json 
"hidden_size": 768,
"vocab_size": 28996

and code is

```
List<String> inputs = new ArrayList<>();
inputs.add("how are you");
Criteria<String[], float[]> criteria = Criteria.builder()
                .setTypes(String[].class, float[].class)
                .optEngine("PyTorch")
                .optModelPath(Paths.get("bert-base-cased.pt"))
                .optTranslator(new CustomBertTranslator())
                .optProgress(new ProgressBar())
                .build();
  try (ZooModel<String[], float[]> model = criteria.loadModel();
       Predictor<String[], float[]> predictor = model.newPredictor()) {
      float[] res = predictor.predict(inputs.toArray(new String[0]));
  }
```

```
@Override
    public NDList processInput(TranslatorContext ctx, String[] inputs) throws Exception {
        path = Paths.get("tokenizer.json");
        try (HuggingFaceTokenizer tokenizer = HuggingFaceTokenizer.newInstance(path)) {
            Encoding encoding = tokenizer.encode(inputs[0]);
            List<String>  tokens = tokenizer.tokenize(inputs[0]);
            NDManager manager = ctx.getNDManager();
            long[] indices = encoding.getIds();
            NDArray indicesArray = manager.create(indices);
            long[] attention_mask  = encoding.getAttentionMask();
            NDArray attentionMaskArray = manager.create(attention_mask);
            return new NDList(indicesArray,attentionMaskArray);
      }
  } 
   @Override
    public float[] processOutput(TranslatorContext ctx, NDList list) {
        NDArray outputarray = list.get(0);
        Shape shape = outputarray.getShape();
        long length = shape.get(0);
        long veclength = shape.get(1);
        float[] vec = new float[(int) veclength];
        for (int i=0;i<veclength;i++){
            float sum = 0f;
            for (int j=1;j<length-1;j++){
                sum += outputarray.get(j).getFloat(i);
            }
            vec[i] = sum / length-2;
        }
        System.out.println(Arrays.toString(vec));
        return vec;
  }
```

i have two questions
1、why i get output ndlist shape is (5,28896), not 768，is something error in my code?
2、i want to get textembedding,and i use sum to average , is  it correct to use bert-base model to get textembedding?

thank you for your help

**Comment by frankfliu** [comment]
You'd better use sentence transformer models for text embedding, for example: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

You can use our built-in model zoo directly: https://github.com/deepjavalibrary/djl-demo/blob/master/huggingface/nlp/src/main/java/com/examples/TextEmbedding.java#L37

Please take a look our built-in TextEmbeddingTranslator: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java#L67-L74

**Comment by yjh01** [comment]
thank you for your answer
i still have a question
when i use multilingual  language model ,it's embedding  not correct for chinese , but model_zoo_importer.py is not support for only chinese model. so  how can i get a chinese model. is only hide this code in huggingface_models.py?

```
 if "en" not in languages:
                logging.warning(f"Skip non-English model: {model_id}.")
                continue
```

i learn python recently , so i read py file hard
thank you for your help

**Comment by frankfliu** [comment]
The tool you are referring to is used import a HuggingFace model from huggingface hub. We only tested english model, that's why we filtered out other languages. You can try other models by modify this tool. But you need verify if the traced model is work as expected and the built-in translator works for you.

**Comment by yjh01** [comment]
@frankfliu 
Thank you for your help
I has slove the  model. But now , i have a new Problem.
My linux System is not  allowed link outside network. But pytorch engine need download some file. How can i slove this problem

code exception
```
ai.djl.engine.EngineException: Failed to save pytorch index file
	at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:396)
	at ai.djl.pytorch.jni.LibUtils.findNativeLibrary(LibUtils.java:286)
	at ai.djl.pytorch.jni.LibUtils.getLibTorch(LibUtils.java:89)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:77)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:53)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:187)
	at ai.djl.Model.newInstance(Model.java:99)
```

**Comment by frankfliu** [comment]
You can package native library in your distribution to avoid DJL download .so files at runtime.
See: https://github.com/deepjavalibrary/djl-demo/blob/master/development/fatjar/README.md

You can also set `-Doffline=true` to ensure your configuration is correct
